
[tool.poetry]
name = "python-template"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]

[tool.poetry.dependencies]
python = ">=3.11"
colorama = ">=0.4.6"
discord-py = ">=2.4.0"
pystyle = ">=2.9"
requests = ">=2.32.3"
